//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DivorceCortana.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>AdobeFlashPlayerUpdateSvc</string>
  <string>DiagTrack</string>
  <string>dmwappushservice</string>
  <string>DPS</string>
  <string>ibtsiva</string>
  <string>igfxCUIService1.0.0.0</string>
  <string>igfxCUIService2.0.0.0</string>
  <string>nvsvc</string>
  <string>NvTelemetryContainer</string>
  <string>RetailDemo</string>
  <string>TrkWks</string>
  <string>WdiServiceHost</string>
  <string>Net Driver HPZ12</string>
  <string>Pml Driver HPZ12</string>
  <string>SQLTELEMETRY</string>
  <string>SSISTELEMETRY130</string>
  <string>SQLTELEMETRY$SQLEXPRESS</string>
  <string>SQLTELEMETRY$MSSQLSERVER</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ServicesToDelete {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ServicesToDelete"]));
            }
            set {
                this["ServicesToDelete"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>AdobeFlashPlayerUpdateSvc</string>\r\n  <string>AppReadiness</string>\r\n  <st" +
            "ring>AppXSvc</string>\r\n  <string>BcmBtRSupport</string>\r\n  <string>Browser</stri" +
            "ng>\r\n  <string>CDPSvc</string>\r\n  <string>CDPUserSvc</string>\r\n  <string>cphs</s" +
            "tring>\r\n  <string>DevicesFlowUserSvc</string>\r\n  <string>diagnosticshub.standard" +
            "collector.service</string>\r\n  <string>diagsvc</string>\r\n  <string>DiagTrack</str" +
            "ing>\r\n  <string>dmwappushservice</string>\r\n  <string>DoSvc</string>\r\n  <string>D" +
            "PS</string>\r\n  <string>DsSvc</string>\r\n  <string>FrameServer</string>\r\n  <string" +
            ">HomeGroupListener</string>\r\n  <string>HomeGroupProvider</string>\r\n  <string>ibt" +
            "siva</string>\r\n  <string>icssvc</string>\r\n  <string>igfxCUIService2.0.0.0</strin" +
            "g>\r\n  <string>InstallService</string>\r\n  <string>lfsvc</string>\r\n  <string>MapsB" +
            "roker</string>\r\n  <string>MessagingService</string>\r\n  <string>MpsSvc</string>\r\n" +
            "  <string>NcbService</string>\r\n  <string>NvTelemetryContainer</string>\r\n  <strin" +
            "g>OneSyncSvc</string>\r\n  <string>PimIndexMaintenanceSvc</string>\r\n  <string>Reta" +
            "ilDemo</string>\r\n  <string>RmSvc</string>\r\n  <string>Sense</string>\r\n  <string>S" +
            "ensorDataService</string>\r\n  <string>SensorService</string>\r\n  <string>SensrSvc<" +
            "/string>\r\n  <string>spectrum</string>\r\n  <string>SysMain</string>\r\n  <string>Tab" +
            "letInputService</string>\r\n  <string>TokenBroker</string>\r\n  <string>TrkWks</stri" +
            "ng>\r\n  <string>UnistoreSvc</string>\r\n  <string>UserDataSvc</string>\r\n  <string>W" +
            "bioSrvc</string>\r\n  <string>WdiServiceHost</string>\r\n  <string>WdiSystemHost</st" +
            "ring>\r\n  <string>WdNisSvc</string>\r\n  <string>wercplsupport</string>\r\n  <string>" +
            "WerSvc</string>\r\n  <string>WinDefend</string>\r\n  <string>wisvc</string>\r\n  <stri" +
            "ng>wlidsvc</string>\r\n  <string>WMPNetworkSvc</string>\r\n  <string>WpnService</str" +
            "ing>\r\n  <string>WpnUserService</string>\r\n  <string>wudfsvc</string>\r\n  <string>x" +
            "bgm</string>\r\n  <string>XblAuthManager</string>\r\n  <string>XblGameSave</string>\r" +
            "\n  <string>XboxGipSvc</string>\r\n  <string>XboxNetApiSvc</string>\r\n  <string>odse" +
            "rv</string>\r\n  <string>DusmSvc</string>\r\n  <string>NgcSvc</string>\r\n  <string>Pc" +
            "aSvc</string>\r\n  <string>LicenseManager</string>\r\n  <string>NgcCtnrSvc</string>\r" +
            "\n  <string>SQLTELEMETRY</string>\r\n  <string>SSISTELEMETRY130</string>\r\n  <string" +
            ">SQLTELEMETRY$SQLEXPRESS</string>\r\n  <string>SQLTELEMETRY$MSSQLSERVER</string>\r\n" +
            "</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ServicesToDisable {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ServicesToDisable"]));
            }
            set {
                this["ServicesToDisable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>C:\Windows\System32\Tasks\Microsoft\Windows\DiskDiagnostic</string>
  <string>C:\Windows\System32\Tasks\Microsoft\Windows\Customer Experience Improvement Program</string>
  <string>C:\Windows\System32\Tasks\Microsoft\Windows\Diagnosis</string>
  <string>C:\Windows\System32\Tasks\Microsoft\Windows\Windows Media Sharing</string>
  <string>C:\Windows\System32\Tasks\Microsoft\Windows\GWX</string>
  <string>C:\Windows\System32\Tasks\Microsoft\Windows\Windows Error Reporting</string>
  <string>C:\Windows\System32\Tasks\Microsoft\Windows\Power Efficiency Diagnostics</string>
  <string>C:\Windows\System32\Tasks\Microsoft\Windows\Feedback</string>
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection FoldersToDelete {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["FoldersToDelete"]));
            }
            set {
                this["FoldersToDelete"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>C:\Windows\System32\Tasks\Adobe Flash Player Updater</string>
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
  <string />
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection FilesToDelete {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["FilesToDelete"]));
            }
            set {
                this["FilesToDelete"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>C:\Windows\System32\generaltel.dll</string>
  <string>C:\Windows\System32\diagtrack.dll</string>
  <string>C:\Windows\System32\diagtrack_win.dll</string>
  <string>C:\Windows\System32\diagtrack_wininternal.dll</string>
  <string>C:\Windows\System32\UtcResources.dll</string>
  <string>C:\Windows\System32\wsqmcons.exe</string>
  <string>C:\Windows\System32\WSCollect.exe</string>
  <string>C:\Windows\System32\WerFault.exe</string>
  <string>C:\Windows\System32\WerFaultSecure.exe</string>
  <string>C:\Program Files\Microsoft SQL Server\MSSQL13.SQLEXPRESS\MSSQL\Binn\sqlceip.exe</string>
  <string>C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\Binn\sqlceip.exe</string>
  <string>C:\Program Files\Microsoft SQL Server\MSRS13.SQLEXPRESS\MSSQL\Binn\sqlceip.exe</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection FilesToDisable {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["FilesToDisable"]));
            }
            set {
                this["FilesToDisable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>C:\Windows\System32\DiagSvcs</string>
  <string>C:\Windows10Upgrade</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection FoldersToDisable {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["FoldersToDisable"]));
            }
            set {
                this["FoldersToDisable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Adobe Flash Player Updater</string>
  <string>OneDrive Standalone Update Task v2</string>
  <string>Open URL by RoboForm</string>
  <string>Run RoboForm TaskBar Icon</string>
  <string>Adobe Flash Player NPAPI Notifier</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection TasksToDelete {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["TasksToDelete"]));
            }
            set {
                this["TasksToDelete"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>\Microsoft\Windows Defender</string>
  <string>\Microsoft\Windows\Application Experience</string>
  <string>\Microsoft\Windows\ApplicationData</string>
  <string>\Microsoft\Windows\CloudExperienceHost</string>
  <string>\Microsoft\Windows\Customer Experience Improvement Program</string>
  <string>\Microsoft\Windows\Diagnosis</string>
  <string>\Microsoft\Windows\DiskDiagnostic</string>
  <string>\Microsoft\Windows\GWX</string>
  <string>\Microsoft\Windows\Power Efficiency Diagnostics</string>
  <string>\Microsoft\Windows\Windows Activation Technologies</string>
  <string>\Microsoft\Windows\Windows Error Reporting</string>
  <string>\Microsoft\Windows\Windows Media Sharing</string>
  <string>\Microsoft\Windows\Wininet</string>
  <string>\Microsoft\Windows\Feedback\Siuf</string>
  <string>\Microsoft\Windows\Feedback</string>
  <string>\Microsoft\Windows\RetailDemo</string>
  <string>\Microsoft\Windows\Maintenance\WinSAT</string>
  <string>\Microsoft\Windows\RAC</string>
  <string>\Microsoft\Windows\Location</string>
  <string>\Microsoft\Windows\Autochk</string>
  <string>\Microsoft\Windows\Media Center</string>
  <string>\Microsoft\Windows\PerfTrack</string>
  <string>\Microsoft\Windows\SettingSync</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection TaskFoldersToDelete {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["TaskFoldersToDelete"]));
            }
            set {
                this["TaskFoldersToDelete"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>%userprofile%\AppData\Roaming\vstelemetry</string>
  <string>%userprofile%\AppData\Roaming\Mozilla\Firefox\Crash Reports</string>
  <string>C:\ProgramData\Microsoft\Diagnosis</string>
  <string>c:\programdata\microsoft\windows\wer</string>
  <string>C:\programdata\microsoft\windows\Caches</string>
  <string>C:\programdata\microsoft\windows\Power Efficiency Diagnostics</string>
  <string>C:\Windows\PCHEALTH</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection FoldersToDisableAndRemoveFiles {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["FoldersToDisableAndRemoveFiles"]));
            }
            set {
                this["FoldersToDisableAndRemoveFiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>C:\\Program Files\\Microsoft Office\\Office15\\GROOVEEX.DLL</string>\r\n</ArrayO" +
            "fString>")]
        public global::System.Collections.Specialized.StringCollection DeregisterDll {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["DeregisterDll"]));
            }
            set {
                this["DeregisterDll"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>CDPSvc</string>
  <string>CDPUserSvc</string>
  <string>diagnosticshub.standardcollector.service</string>
  <string>PimIndexMaintenanceSvc</string>
  <string>WpnUserService</string>
  <string>WpnService</string>
  <string>UserDataSvc</string>
  <string>OneSyncSvc</string>
  <string>WdiServiceHost</string>
  <string>WdiSystemHost</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ServicesToUnImage {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ServicesToUnImage"]));
            }
            set {
                this["ServicesToUnImage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>CortanaListenUIApp</string>\r\n  <string>DesktopLearning</string>\r\n  <string" +
            ">DesktopView</string>\r\n  <string>EnvironmentsApp</string>\r\n  <string>holocamera<" +
            "/string>\r\n  <string>holoitemplayerapp</string>\r\n  <string>InsiderHub</string>\r\n " +
            " <string>Microsoft.AAD.BrokerPlugin</string>\r\n  <string>Microsoft.AccountsContro" +
            "l</string>\r\n  <string>Microsoft.BioEnrollment</string>\r\n  <string>microsoft.cred" +
            "dialoghost</string>\r\n  <string>Microsoft.LockApp</string>\r\n  <string>Microsoft.M" +
            "icrosoftEdge</string>\r\n  <string>Microsoft.PPIProjection</string>\r\n  <string>Mic" +
            "rosoft.Windows.AppRep.ChxApp</string>\r\n  <string>Microsoft.Windows.AppResolverUX" +
            "</string>\r\n  <string>Microsoft.Windows.AssignedAccessLockApp</string>\r\n  <string" +
            ">Microsoft.Windows.CloudExperienceHost</string>\r\n  <string>Microsoft.Windows.Con" +
            "tentDeliveryManager</string>\r\n  <string>Microsoft.Windows.Cortana</string>\r\n  <s" +
            "tring>Microsoft.Windows.HolographicFirstRun</string>\r\n  <string>Microsoft.Window" +
            "s.ModalSharePickerHost</string>\r\n  <string>Microsoft.Windows.OOBENetworkCaptiveP" +
            "ortal</string>\r\n  <string>Microsoft.Windows.OOBENetworkConnectionFlow</string>\r\n" +
            "  <string>Microsoft.Windows.SecHealthUI</string>\r\n  <string>Microsoft.Windows.Se" +
            "condaryTileExperience</string>\r\n  <string>Microsoft.Windows.SecureAssessmentBrow" +
            "ser</string>\r\n  <string>Microsoft.Windows.WindowPicker</string>\r\n  <string>Micro" +
            "soft.XboxGameCallableUI</string>\r\n  <string>ParentalControls</string>\r\n</ArrayOf" +
            "String>")]
        public global::System.Collections.Specialized.StringCollection SystemAppsToDelete {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["SystemAppsToDelete"]));
            }
            set {
                this["SystemAppsToDelete"] = value;
            }
        }
    }
}
